[package]
name = "point_set"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bits = {git = "https://github.com/gjf2a/bits"}